export { HermesClient } from "./client";
export {
  Document,
  SearchHit,
  SearchResponse,
  IndexInfo,
  SearchOptions,
  TermQuery,
  BooleanQueryDef,
  SparseVectorQueryDef,
  SparseTextQueryDef,
  DenseVectorQueryDef,
  RerankerDef,
  Combiner,
  RerankerCombiner,
} from "./types";

export {
  SearchServiceDefinition,
  IndexServiceDefinition,
  MultiValueCombiner,
  Query,
  TermQuery as PbTermQuery,
  BooleanQuery,
  BoostQuery,
  AllQuery,
  MatchQuery,
  SparseVectorQuery,
  DenseVectorQuery,
  Reranker,
  SearchRequest,
  SearchResponse as PbSearchResponse,
  SearchHit as PbSearchHit,
  FieldValue,
  FieldEntry,
  SparseVector,
  DenseVector,
  GetDocumentRequest,
  GetDocumentResponse,
  GetIndexInfoRequest,
  GetIndexInfoResponse,
  CreateIndexRequest,
  CreateIndexResponse,
  IndexDocumentRequest,
  IndexDocumentsResponse,
  BatchIndexDocumentsRequest,
  BatchIndexDocumentsResponse,
  NamedDocument,
  CommitRequest,
  CommitResponse,
  ForceMergeRequest,
  ForceMergeResponse,
  DeleteIndexRequest,
  DeleteIndexResponse,
  ListIndexesRequest,
  ListIndexesResponse,
  MemoryStats,
  IndexingBufferStats,
  SegmentReaderStats,
  OrdinalScore,
} from "./generated/hermes";
