export { HermesClient } from "./client";
export type {
  DocAddress,
  Document,
  SearchHit,
  SearchResponse,
  SearchTimings,
  IndexInfo,
  VectorFieldStats,
  SearchRequest,
  Query,
  TermQuery,
  MatchQuery,
  BooleanQuery,
  BoostQuery,
  AllQuery,
  SparseVectorQuery,
  DenseVectorQuery,
  RangeQuery,
  Combiner,
  Reranker,
} from "./types";

export {
  SearchServiceDefinition,
  IndexServiceDefinition,
  MultiValueCombiner,
  Query as PbQuery,
  TermQuery as PbTermQuery,
  BooleanQuery as PbBooleanQuery,
  BoostQuery as PbBoostQuery,
  AllQuery as PbAllQuery,
  MatchQuery as PbMatchQuery,
  SparseVectorQuery as PbSparseVectorQuery,
  DenseVectorQuery as PbDenseVectorQuery,
  Reranker as PbReranker,
  SearchRequest as PbSearchRequest,
  SearchResponse as PbSearchResponse,
  SearchHit as PbSearchHit,
  FieldValue,
  FieldEntry,
  SparseVector,
  DenseVector,
  GetDocumentRequest,
  DocAddress as PbDocAddress,
  GetDocumentResponse,
  GetIndexInfoRequest,
  GetIndexInfoResponse,
  CreateIndexRequest,
  CreateIndexResponse,
  IndexDocumentRequest,
  IndexDocumentsResponse,
  BatchIndexDocumentsRequest,
  BatchIndexDocumentsResponse,
  NamedDocument,
  CommitRequest,
  CommitResponse,
  ForceMergeRequest,
  ForceMergeResponse,
  DeleteIndexRequest,
  DeleteIndexResponse,
  ListIndexesRequest,
  ListIndexesResponse,
  MemoryStats,
  IndexingBufferStats,
  SegmentReaderStats,
  OrdinalScore,
} from "./generated/hermes";
